/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.HashSet;

/**
 *
 * @author ALUNO
 */
public class ListaDeLivrosEmprestados extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeLivrosEmprestados
     */
    public ListaDeLivrosEmprestados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPainel = new javax.swing.JPanel();
        escreva1 = new javax.swing.JLabel();
        livroI = new javax.swing.JLabel();
        penalBranco = new javax.swing.JPanel();
        escrevaLista = new javax.swing.JLabel();
        simboloPonto = new javax.swing.JLabel();
        filtrar = new javax.swing.JComboBox<>();
        tabelaRolagem = new javax.swing.JScrollPane();
        priTabela = new javax.swing.JTable();
        botao1 = new javax.swing.JButton();
        menuDeNavegacao = new javax.swing.JMenuBar();
        guiaRegistroEmprestimo = new javax.swing.JMenu();
        guiaListaLivrosEmprestados = new javax.swing.JMenu();
        guiaCadastroLivros = new javax.swing.JMenu();
        guiaListaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBancoDadosTurmas = new javax.swing.JMenu();
        guiaGrafico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Livros Emprestados");

        principalPainel.setBackground(new java.awt.Color(208, 224, 235));

        escreva1.setBackground(new java.awt.Color(0, 0, 0));
        escreva1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        escreva1.setForeground(new java.awt.Color(0, 0, 0));
        escreva1.setText("Biblioteca Syncria");

        livroI.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro_(1)_(2).png")); // NOI18N

        penalBranco.setBackground(new java.awt.Color(73, 112, 138));

        escrevaLista.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        escrevaLista.setForeground(new java.awt.Color(0, 0, 0));
        escrevaLista.setText("Lista de Livros Emprestados");

        simboloPonto.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro emp. 64.png")); // NOI18N

        filtrar.setBackground(new java.awt.Color(255, 255, 255));
        filtrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filtrar.setForeground(new java.awt.Color(0, 0, 0));
        filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar", "Ordem Alfabética", "Número de Códigos", "Data", "Turma", "Bimestre" }));
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        priTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Turno", "Código", "Alunos", "Nome do Livro", "Registro", "Data de Devolução", "Bimestre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRolagem.setViewportView(priTabela);

        botao1.setBackground(new java.awt.Color(255, 255, 255));
        botao1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao1.setForeground(new java.awt.Color(0, 0, 0));
        botao1.setText("Exportar Lista");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout penalBrancoLayout = new javax.swing.GroupLayout(penalBranco);
        penalBranco.setLayout(penalBrancoLayout);
        penalBrancoLayout.setHorizontalGroup(
            penalBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penalBrancoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(penalBrancoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(simboloPonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escrevaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1243, Short.MAX_VALUE)
                .addComponent(botao1)
                .addGap(37, 37, 37))
            .addComponent(tabelaRolagem)
        );
        penalBrancoLayout.setVerticalGroup(
            penalBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penalBrancoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(penalBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penalBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao1)
                        .addComponent(escrevaLista))
                    .addComponent(simboloPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(tabelaRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout principalPainelLayout = new javax.swing.GroupLayout(principalPainel);
        principalPainel.setLayout(principalPainelLayout);
        principalPainelLayout.setHorizontalGroup(
            principalPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPainelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(livroI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escreva1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(principalPainelLayout.createSequentialGroup()
                .addComponent(penalBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        principalPainelLayout.setVerticalGroup(
            principalPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPainelLayout.createSequentialGroup()
                .addGroup(principalPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPainelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(livroI, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(escreva1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penalBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guiaRegistroEmprestimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\registro.png")); // NOI18N
        guiaRegistroEmprestimo.setText(" Registro de Empréstimo |");
        guiaRegistroEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRegistroEmprestimoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRegistroEmprestimo);

        guiaListaLivrosEmprestados.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro emp. 24.png")); // NOI18N
        guiaListaLivrosEmprestados.setText("Lista de Livros Emprestados |");
        guiaListaLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosEmprestadosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaLivrosEmprestados);

        guiaCadastroLivros.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\cadastro de livros 24.png")); // NOI18N
        guiaCadastroLivros.setText("Cadastro de Livros |");
        guiaCadastroLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaCadastroLivrosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaCadastroLivros);

        guiaListaLivrosAcervo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\open-book.png")); // NOI18N
        guiaListaLivrosAcervo.setText("Lista de Livros no Acervo |");
        guiaListaLivrosAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosAcervoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaLivrosAcervo);

        guiaRankingLeitores.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\ranking.png")); // NOI18N
        guiaRankingLeitores.setText("Ranking dos Leitores |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRankingLeitores);

        guiaBancoDadosTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\grupo-de-usuarios_(1).png")); // NOI18N
        guiaBancoDadosTurmas.setText("Banco de Dados das Turmas |");
        guiaBancoDadosTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBancoDadosTurmasMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaBancoDadosTurmas);

        guiaGrafico.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\line-chart.png")); // NOI18N
        menuDeNavegacao.add(guiaGrafico);

        setJMenuBar(menuDeNavegacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botao1ActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_filtrarActionPerformed

    
    private void guiaListaLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosEmprestadosMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_guiaListaLivrosEmprestadosMouseClicked

    private void guiaBancoDadosTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBancoDadosTurmasMouseClicked
        // TODO add your handling code here:
          
        //criar objeto da classe 
        BancoDeDadosDasTurmas bancoDadosTurma = new BancoDeDadosDasTurmas();
               // abrindo a tela
                bancoDadosTurma.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaBancoDadosTurmasMouseClicked

    private void guiaListaLivrosAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosAcervoMouseClicked

        // TODO add your handling code here:
        
        //criar objeto da classe 
        ListaDeLivrosNoAcervo livrosAcervo = new ListaDeLivrosNoAcervo();
               // abrindo a tela
                livrosAcervo.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
        
    }//GEN-LAST:event_guiaListaLivrosAcervoMouseClicked

    private void guiaRegistroEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRegistroEmprestimoMouseClicked
        // TODO add your handling code here:
        
        //criar objeto da classe 
        TelaRegistrosEmprestimos registroEmprestimo = new TelaRegistrosEmprestimos();
               // abrindo a tela
                registroEmprestimo.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
            
            
    }//GEN-LAST:event_guiaRegistroEmprestimoMouseClicked

    private void guiaCadastroLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaCadastroLivrosMouseClicked
        // TODO add your handling code here
        
                //criar objeto da classe 
        Telaldecadastrodelivros cadastroLivro = new Telaldecadastrodelivros();
               // abrindo a tela
                cadastroLivro.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaCadastroLivrosMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    
    
    
    
    
    
    /**  * 
@param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeLivrosEmprestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeLivrosEmprestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeLivrosEmprestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeLivrosEmprestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeLivrosEmprestados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JLabel escreva1;
    private javax.swing.JLabel escrevaLista;
    private javax.swing.JComboBox<String> filtrar;
    private javax.swing.JMenu guiaBancoDadosTurmas;
    private javax.swing.JMenu guiaCadastroLivros;
    private javax.swing.JMenu guiaGrafico;
    private javax.swing.JMenu guiaListaLivrosAcervo;
    private javax.swing.JMenu guiaListaLivrosEmprestados;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JMenu guiaRegistroEmprestimo;
    private javax.swing.JLabel livroI;
    private javax.swing.JMenuBar menuDeNavegacao;
    private javax.swing.JPanel penalBranco;
    private javax.swing.JTable priTabela;
    private javax.swing.JPanel principalPainel;
    private javax.swing.JLabel simboloPonto;
    private javax.swing.JScrollPane tabelaRolagem;
    // End of variables declaration//GEN-END:variables
}
