/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaRankingDeLeitores extends javax.swing.JFrame {

    /**
     * Creates new form BancoDeDadosDasTurmas
     */
    public TelaRankingDeLeitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        painelPrincipalFundo = new javax.swing.JPanel();
        filtroTurma = new javax.swing.JComboBox<>();
        filtroTurnos = new javax.swing.JComboBox<>();
        botaoDeFiltrar = new javax.swing.JButton();
        botaoExportar = new javax.swing.JButton();
        cabecalhoSyncria = new javax.swing.JPanel();
        letreiroSyncria = new javax.swing.JLabel();
        iconeDoLivroSyncria = new javax.swing.JLabel();
        iconeUsuariosBDDadosdasTurmas = new javax.swing.JLabel();
        letreiroBDdasTurmas = new javax.swing.JLabel();
        linhaDeSeparar = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaBDTurmas = new javax.swing.JTable();
        menuDeNavegacao = new javax.swing.JMenuBar();
        guiaRegistroDeEmprestimo = new javax.swing.JMenu();
        guiaListaDeLivrosEmprestados = new javax.swing.JMenu();
        guiaCadastroDeLivros = new javax.swing.JMenu();
        guiaListaDeLivrosNoAcervo = new javax.swing.JMenu();
        guiaRankingDosLeitores = new javax.swing.JMenu();
        guiaBancoDeDadosDasTurmas = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de Dados das Turmas");

        painelPrincipalFundo.setBackground(new java.awt.Color(73, 112, 138));

        filtroTurma.setBackground(new java.awt.Color(255, 255, 255));
        filtroTurma.setForeground(new java.awt.Color(0, 0, 0));
        filtroTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURMA" }));
        filtroTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTurmaActionPerformed(evt);
            }
        });

        filtroTurnos.setBackground(new java.awt.Color(255, 255, 255));
        filtroTurnos.setForeground(new java.awt.Color(0, 0, 0));
        filtroTurnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURNO", "MATUTINO", "VESPERTINO", "NOTURNO" }));
        filtroTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTurnosActionPerformed(evt);
            }
        });

        botaoDeFiltrar.setBackground(new java.awt.Color(255, 255, 255));
        botaoDeFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        botaoDeFiltrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\icons8-filtro-vazio-50 (2).png")); // NOI18N
        botaoDeFiltrar.setText("Filtrar");
        botaoDeFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeFiltrarActionPerformed(evt);
            }
        });

        botaoExportar.setBackground(new java.awt.Color(255, 255, 255));
        botaoExportar.setForeground(new java.awt.Color(0, 0, 0));
        botaoExportar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\exportar.png")); // NOI18N
        botaoExportar.setText("Exportar");

        cabecalhoSyncria.setBackground(new java.awt.Color(208, 224, 235));
        cabecalhoSyncria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        letreiroSyncria.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        letreiroSyncria.setForeground(new java.awt.Color(0, 0, 0));
        letreiroSyncria.setText("Biblioteca Syncria");

        iconeDoLivroSyncria.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro (1) (2).png")); // NOI18N

        javax.swing.GroupLayout cabecalhoSyncriaLayout = new javax.swing.GroupLayout(cabecalhoSyncria);
        cabecalhoSyncria.setLayout(cabecalhoSyncriaLayout);
        cabecalhoSyncriaLayout.setHorizontalGroup(
            cabecalhoSyncriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconeDoLivroSyncria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letreiroSyncria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabecalhoSyncriaLayout.setVerticalGroup(
            cabecalhoSyncriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(letreiroSyncria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(iconeDoLivroSyncria)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        iconeUsuariosBDDadosdasTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\ranking (2).png")); // NOI18N

        letreiroBDdasTurmas.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        letreiroBDdasTurmas.setForeground(new java.awt.Color(0, 0, 0));
        letreiroBDdasTurmas.setText("Ranking de Leitores");

        linhaDeSeparar.setBackground(new java.awt.Color(0, 0, 0));
        linhaDeSeparar.setForeground(new java.awt.Color(0, 0, 0));

        tabelaBDTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Turma", "Nomes", "Livros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaBDTurmas.setToolTipText("");
        jScrollPane2.setViewportView(tabelaBDTurmas);

        javax.swing.GroupLayout painelPrincipalFundoLayout = new javax.swing.GroupLayout(painelPrincipalFundo);
        painelPrincipalFundo.setLayout(painelPrincipalFundoLayout);
        painelPrincipalFundoLayout.setHorizontalGroup(
            painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalhoSyncria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(linhaDeSeparar)
            .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                        .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(iconeUsuariosBDDadosdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(letreiroBDdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(filtroTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(filtroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoDeFiltrar)
                                .addGap(30, 30, 30)
                                .addComponent(botaoExportar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelPrincipalFundoLayout.setVerticalGroup(
            painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalFundoLayout.createSequentialGroup()
                .addComponent(cabecalhoSyncria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                        .addComponent(iconeUsuariosBDDadosdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalFundoLayout.createSequentialGroup()
                        .addComponent(letreiroBDdasTurmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(linhaDeSeparar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDeFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExportar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1114, Short.MAX_VALUE))
        );

        guiaRegistroDeEmprestimo.setText("| Registro de Empréstimo |");
        guiaRegistroDeEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRegistroDeEmprestimoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRegistroDeEmprestimo);

        guiaListaDeLivrosEmprestados.setText("Lista de Livros Emprestados |");
        guiaListaDeLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaDeLivrosEmprestadosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaDeLivrosEmprestados);

        guiaCadastroDeLivros.setText("Cadastro de Livros |");
        guiaCadastroDeLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaCadastroDeLivrosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaCadastroDeLivros);

        guiaListaDeLivrosNoAcervo.setText("Lista de Livros no Acervo |");
        guiaListaDeLivrosNoAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaDeLivrosNoAcervoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaDeLivrosNoAcervo);

        guiaRankingDosLeitores.setText("Ranking dos Leitores |");
        guiaRankingDosLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingDosLeitoresMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRankingDosLeitores);

        guiaBancoDeDadosDasTurmas.setText("Banco de Dados das Turmas |");
        guiaBancoDeDadosDasTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBancoDeDadosDasTurmasMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaBancoDeDadosDasTurmas);

        setJMenuBar(menuDeNavegacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelPrincipalFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDeFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDeFiltrarActionPerformed

    private void filtroTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTurmaActionPerformed

    private void filtroTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTurnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTurnosActionPerformed

    private void guiaBancoDeDadosDasTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBancoDeDadosDasTurmasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaBancoDeDadosDasTurmasMouseClicked

    private void guiaRegistroDeEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRegistroDeEmprestimoMouseClicked
        // TODO add your handling code here:
        TelaRegistrosEmprestimos tela6ParaTela1 = new TelaRegistrosEmprestimos();
        
        //Abrindo a tela 6 para tela 1
        tela6ParaTela1.setVisible(true);
        
        //Fechando a tela de login
        dispose();
    }//GEN-LAST:event_guiaRegistroDeEmprestimoMouseClicked

    private void guiaListaDeLivrosNoAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaDeLivrosNoAcervoMouseClicked
        // TODO add your handling code here:
        
        //acesso da tela 6 para tela 4
        ListaDeLivrosNoAcervo tela6ParaTela4 = new  ListaDeLivrosNoAcervo();
        
        //Abrindo a tela
        tela6ParaTela4.setVisible(true);
        
        //Fechando a tela de login
        dispose();
    }//GEN-LAST:event_guiaListaDeLivrosNoAcervoMouseClicked

    private void guiaRankingDosLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingDosLeitoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaRankingDosLeitoresMouseClicked

    private void guiaCadastroDeLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaCadastroDeLivrosMouseClicked
        // TODO add your handling code here:
        
        //acesso da Tela 6 para tela 3
        TelaDeCadastroDeLivros tela6paratela3 = new  TelaDeCadastroDeLivros ();
        
        //Abrindo a tela
        tela6paratela3.setVisible(true);
        
        //Fechando a tela de login
        dispose();
    }//GEN-LAST:event_guiaCadastroDeLivrosMouseClicked

    private void guiaListaDeLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaDeLivrosEmprestadosMouseClicked
        // TODO add your handling code here:
        
        //acesso da Tela 6 para tela 2
        ListaDeLivrosEmprestados tela6paratela2 = new  ListaDeLivrosEmprestados ();
        
        //Abrindo a tela
        tela6paratela2.setVisible(true);
        
        //Fechando a tela de login
        dispose();
    }//GEN-LAST:event_guiaListaDeLivrosEmprestadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRankingDeLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRankingDeLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRankingDeLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRankingDeLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRankingDeLeitores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeFiltrar;
    private javax.swing.JButton botaoExportar;
    private javax.swing.JPanel cabecalhoSyncria;
    private javax.swing.JComboBox<String> filtroTurma;
    private javax.swing.JComboBox<String> filtroTurnos;
    private javax.swing.JMenu guiaBancoDeDadosDasTurmas;
    private javax.swing.JMenu guiaCadastroDeLivros;
    private javax.swing.JMenu guiaListaDeLivrosEmprestados;
    private javax.swing.JMenu guiaListaDeLivrosNoAcervo;
    private javax.swing.JMenu guiaRankingDosLeitores;
    private javax.swing.JMenu guiaRegistroDeEmprestimo;
    private javax.swing.JLabel iconeDoLivroSyncria;
    private javax.swing.JLabel iconeUsuariosBDDadosdasTurmas;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel letreiroBDdasTurmas;
    private javax.swing.JLabel letreiroSyncria;
    private javax.swing.JSeparator linhaDeSeparar;
    private javax.swing.JMenuBar menuDeNavegacao;
    private javax.swing.JPanel painelPrincipalFundo;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tabelaBDTurmas;
    // End of variables declaration//GEN-END:variables
}
