/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class Telalogin extends javax.swing.JFrame {

    /**
     * Creates new form Telalogin
     */
    public Telalogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tela1 = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        escrevaGmail = new javax.swing.JTextField();
        butaoSenha = new javax.swing.JButton();
        senhaLogin = new javax.swing.JPasswordField();
        imagemEmpresa = new javax.swing.JLabel();
        labelEgmail1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 0, 0));

        tela1.setBackground(new java.awt.Color(73, 112, 138));

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelLogin.setForeground(new java.awt.Color(0, 0, 0));
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSenha.setBackground(new java.awt.Color(0, 0, 0));
        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(0, 0, 0));
        labelSenha.setText("Senha:");
        painelLogin.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 20));

        escrevaGmail.setBackground(new java.awt.Color(255, 255, 255));
        escrevaGmail.setForeground(new java.awt.Color(0, 0, 0));
        escrevaGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escrevaGmailActionPerformed(evt);
            }
        });
        painelLogin.add(escrevaGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 20));

        butaoSenha.setBackground(new java.awt.Color(0, 51, 153));
        butaoSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butaoSenha.setForeground(new java.awt.Color(255, 255, 255));
        butaoSenha.setText("Entrar");
        butaoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoSenhaActionPerformed(evt);
            }
        });
        painelLogin.add(butaoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 30));

        senhaLogin.setBackground(new java.awt.Color(255, 255, 255));
        senhaLogin.setForeground(new java.awt.Color(0, 0, 0));
        painelLogin.add(senhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, -1));

        imagemEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        imagemEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Syncria_-_Technology (2).png")); // NOI18N
        painelLogin.add(imagemEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 90));

        labelEgmail1.setBackground(new java.awt.Color(0, 0, 0));
        labelEgmail1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEgmail1.setForeground(new java.awt.Color(0, 0, 0));
        labelEgmail1.setText("Usuário:");
        painelLogin.add(labelEgmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, 20));

        javax.swing.GroupLayout tela1Layout = new javax.swing.GroupLayout(tela1);
        tela1.setLayout(tela1Layout);
        tela1Layout.setHorizontalGroup(
            tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        tela1Layout.setVerticalGroup(
            tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void escrevaGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escrevaGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escrevaGmailActionPerformed

    private void butaoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoSenha;
    private javax.swing.JTextField escrevaGmail;
    private javax.swing.JLabel imagemEmpresa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEgmail1;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPasswordField senhaLogin;
    private javax.swing.JPanel tela1;
    // End of variables declaration//GEN-END:variables
}
