/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaGraficos extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeLivrosNoAcervo
     */
    public TelaGraficos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDeRolagem = new javax.swing.JScrollPane();
        princPanel = new javax.swing.JPanel();
        panelBranco = new javax.swing.JPanel();
        escreva1 = new javax.swing.JLabel();
        livroI = new javax.swing.JLabel();
        graficoIcon = new javax.swing.JLabel();
        escrevaGrafico = new javax.swing.JLabel();
        botAtualizar = new javax.swing.JButton();
        painelTurno = new javax.swing.JPanel();
        qtDeLivEmpTur = new javax.swing.JLabel();
        painelGeneros = new javax.swing.JPanel();
        qtDeLivporGen = new javax.swing.JLabel();
        painelRanking = new javax.swing.JPanel();
        rankDosLeitores = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        qtDeLivEmpTur1 = new javax.swing.JLabel();
        painelBimestre1 = new javax.swing.JPanel();
        qtDeLivEmpporBim2 = new javax.swing.JLabel();
        menugraficos = new javax.swing.JMenuBar();
        guiaRegistroEmprestimo = new javax.swing.JMenu();
        guiaListaLivrosEmprestados = new javax.swing.JMenu();
        guiaCadastroLivros = new javax.swing.JMenu();
        guiaListaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBancoDadosTurmas = new javax.swing.JMenu();
        guiaGrafico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Livros no Acervo");

        princPanel.setBackground(new java.awt.Color(73, 112, 138));
        princPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));

        panelBranco.setBackground(new java.awt.Color(208, 224, 235));

        escreva1.setBackground(new java.awt.Color(255, 255, 255));
        escreva1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        escreva1.setForeground(new java.awt.Color(0, 0, 0));
        escreva1.setText("Biblioteca Syncria");

        livroI.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro_(1)_(2).png")); // NOI18N

        javax.swing.GroupLayout panelBrancoLayout = new javax.swing.GroupLayout(panelBranco);
        panelBranco.setLayout(panelBrancoLayout);
        panelBrancoLayout.setHorizontalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrancoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(livroI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escreva1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1406, Short.MAX_VALUE))
        );
        panelBrancoLayout.setVerticalGroup(
            panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escreva1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(livroI))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        graficoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\line-chart (1).png")); // NOI18N

        escrevaGrafico.setBackground(new java.awt.Color(255, 255, 255));
        escrevaGrafico.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        escrevaGrafico.setForeground(new java.awt.Color(0, 0, 0));
        escrevaGrafico.setText("Gráficos");

        botAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        botAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        botAtualizar.setText("Atualizar");
        botAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtualizarActionPerformed(evt);
            }
        });

        painelTurno.setBackground(new java.awt.Color(208, 224, 235));
        painelTurno.setForeground(new java.awt.Color(73, 112, 138));

        qtDeLivEmpTur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtDeLivEmpTur.setForeground(new java.awt.Color(0, 0, 0));
        qtDeLivEmpTur.setText("Quantidade de Livros Emprestrados por Turno:");

        javax.swing.GroupLayout painelTurnoLayout = new javax.swing.GroupLayout(painelTurno);
        painelTurno.setLayout(painelTurnoLayout);
        painelTurnoLayout.setHorizontalGroup(
            painelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurnoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(qtDeLivEmpTur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTurnoLayout.setVerticalGroup(
            painelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTurnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(qtDeLivEmpTur)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        painelGeneros.setBackground(new java.awt.Color(208, 224, 235));

        qtDeLivporGen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtDeLivporGen.setForeground(new java.awt.Color(0, 0, 0));
        qtDeLivporGen.setText("Quantidade de Livros por Gêneros Literários:");

        javax.swing.GroupLayout painelGenerosLayout = new javax.swing.GroupLayout(painelGeneros);
        painelGeneros.setLayout(painelGenerosLayout);
        painelGenerosLayout.setHorizontalGroup(
            painelGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGenerosLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(qtDeLivporGen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelGenerosLayout.setVerticalGroup(
            painelGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGenerosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(qtDeLivporGen)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        painelRanking.setBackground(new java.awt.Color(208, 224, 235));

        rankDosLeitores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rankDosLeitores.setForeground(new java.awt.Color(0, 0, 0));
        rankDosLeitores.setText("Ranking Dos Leitores:");

        javax.swing.GroupLayout painelRankingLayout = new javax.swing.GroupLayout(painelRanking);
        painelRanking.setLayout(painelRankingLayout);
        painelRankingLayout.setHorizontalGroup(
            painelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRankingLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(rankDosLeitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(325, 325, 325))
        );
        painelRankingLayout.setVerticalGroup(
            painelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRankingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rankDosLeitores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(208, 224, 235));
        jPanel6.setForeground(new java.awt.Color(73, 112, 138));

        qtDeLivEmpTur1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtDeLivEmpTur1.setForeground(new java.awt.Color(0, 0, 0));
        qtDeLivEmpTur1.setText("Quantidade de Livros Emprestrados por Turma:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(qtDeLivEmpTur1)
                .addGap(261, 261, 261))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(qtDeLivEmpTur1)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        painelBimestre1.setBackground(new java.awt.Color(208, 224, 235));

        qtDeLivEmpporBim2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtDeLivEmpporBim2.setForeground(new java.awt.Color(0, 0, 0));
        qtDeLivEmpporBim2.setText("Quantidade de Livros Emprestrados por Bimestre:");

        javax.swing.GroupLayout painelBimestre1Layout = new javax.swing.GroupLayout(painelBimestre1);
        painelBimestre1.setLayout(painelBimestre1Layout);
        painelBimestre1Layout.setHorizontalGroup(
            painelBimestre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBimestre1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(qtDeLivEmpporBim2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBimestre1Layout.setVerticalGroup(
            painelBimestre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBimestre1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(qtDeLivEmpporBim2)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout princPanelLayout = new javax.swing.GroupLayout(princPanel);
        princPanel.setLayout(princPanelLayout);
        princPanelLayout.setHorizontalGroup(
            princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(princPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(princPanelLayout.createSequentialGroup()
                        .addComponent(painelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelBimestre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelGeneros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(princPanelLayout.createSequentialGroup()
                        .addComponent(painelRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(princPanelLayout.createSequentialGroup()
                .addGroup(princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(princPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(graficoIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escrevaGrafico)
                        .addGap(75, 75, 75)
                        .addComponent(botAtualizar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        princPanelLayout.setVerticalGroup(
            princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(princPanelLayout.createSequentialGroup()
                .addComponent(panelBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botAtualizar)
                    .addComponent(graficoIcon)
                    .addGroup(princPanelLayout.createSequentialGroup()
                        .addComponent(escrevaGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(23, 23, 23)
                .addGroup(princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBimestre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(princPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1091, Short.MAX_VALUE))
        );

        painelDeRolagem.setViewportView(princPanel);

        guiaRegistroEmprestimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\registro.png")); // NOI18N
        guiaRegistroEmprestimo.setText(" Registro de Empréstimo |");
        guiaRegistroEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRegistroEmprestimoMouseClicked(evt);
            }
        });
        menugraficos.add(guiaRegistroEmprestimo);

        guiaListaLivrosEmprestados.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro emp. 24.png")); // NOI18N
        guiaListaLivrosEmprestados.setText("Lista de Livros Emprestados |");
        guiaListaLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosEmprestadosMouseClicked(evt);
            }
        });
        menugraficos.add(guiaListaLivrosEmprestados);

        guiaCadastroLivros.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\cadastro de livros 24.png")); // NOI18N
        guiaCadastroLivros.setText("Cadastro de Livros |");
        guiaCadastroLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaCadastroLivrosMouseClicked(evt);
            }
        });
        menugraficos.add(guiaCadastroLivros);

        guiaListaLivrosAcervo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\open-book.png")); // NOI18N
        guiaListaLivrosAcervo.setText("Lista de Livros no Acervo |");
        menugraficos.add(guiaListaLivrosAcervo);

        guiaRankingLeitores.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\ranking.png")); // NOI18N
        guiaRankingLeitores.setText("Ranking dos Leitores |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        menugraficos.add(guiaRankingLeitores);

        guiaBancoDadosTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\grupo-de-usuarios_(1).png")); // NOI18N
        guiaBancoDadosTurmas.setText("Banco de Dados das Turmas |");
        guiaBancoDadosTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBancoDadosTurmasMouseClicked(evt);
            }
        });
        menugraficos.add(guiaBancoDadosTurmas);

        guiaGrafico.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\line-chart.png")); // NOI18N
        menugraficos.add(guiaGrafico);

        setJMenuBar(menugraficos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeRolagem)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guiaRegistroEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRegistroEmprestimoMouseClicked
        // TODO add your handling code here:
        
         
        //criar objeto da classe 
        TelaRegistrosEmprestimos registroEmprestimo = new TelaRegistrosEmprestimos();
               // abrindo a tela
                registroEmprestimo.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaRegistroEmprestimoMouseClicked

    private void guiaListaLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosEmprestadosMouseClicked
        // TODO add your handling code here:
        
        
        //criar objeto da classe 
        ListaDeLivrosEmprestados listaEmprestado = new ListaDeLivrosEmprestados();
               // abrindo a tela
                listaEmprestado.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaListaLivrosEmprestadosMouseClicked

    private void guiaCadastroLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaCadastroLivrosMouseClicked
        // TODO add your handling code here:
        
             //criar objeto da classe 
        Telaldecadastrodelivros cadastroLivro = new Telaldecadastrodelivros();
               // abrindo a tela
                cadastroLivro.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaCadastroLivrosMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    private void guiaBancoDadosTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBancoDadosTurmasMouseClicked
        // TODO add your handling code here:
        
        //criar objeto da classe 
        BancoDeDadosDasTurmas bancoDadosTurma = new BancoDeDadosDasTurmas();
               // abrindo a tela
                bancoDadosTurma.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaBancoDadosTurmasMouseClicked

    private void botAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAtualizarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGraficos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAtualizar;
    private javax.swing.JLabel escreva1;
    private javax.swing.JLabel escrevaGrafico;
    private javax.swing.JLabel graficoIcon;
    private javax.swing.JMenu guiaBancoDadosTurmas;
    private javax.swing.JMenu guiaCadastroLivros;
    private javax.swing.JMenu guiaGrafico;
    private javax.swing.JMenu guiaListaLivrosAcervo;
    private javax.swing.JMenu guiaListaLivrosEmprestados;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JMenu guiaRegistroEmprestimo;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel livroI;
    private javax.swing.JMenuBar menugraficos;
    private javax.swing.JPanel painelBimestre1;
    private javax.swing.JScrollPane painelDeRolagem;
    private javax.swing.JPanel painelGeneros;
    private javax.swing.JPanel painelRanking;
    private javax.swing.JPanel painelTurno;
    private javax.swing.JPanel panelBranco;
    private javax.swing.JPanel princPanel;
    private javax.swing.JLabel qtDeLivEmpTur;
    private javax.swing.JLabel qtDeLivEmpTur1;
    private javax.swing.JLabel qtDeLivEmpporBim2;
    private javax.swing.JLabel qtDeLivporGen;
    private javax.swing.JLabel rankDosLeitores;
    // End of variables declaration//GEN-END:variables
}
