/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.UsuarioModel;

/**
 *
 * @author ALUNO
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tela1Cadastro = new javax.swing.JPanel();
        tela2cadastro = new javax.swing.JPanel();
        usuariocadastro = new javax.swing.JTextField();
        senhaCadastro = new javax.swing.JLabel();
        senhaCasatro1 = new javax.swing.JPasswordField();
        butaoCadastrar = new javax.swing.JButton();
        usuarioCadastro = new javax.swing.JLabel();
        usuarioCPF = new javax.swing.JLabel();
        usuarioCPFDdigitado = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tela1Cadastro.setBackground(new java.awt.Color(73, 112, 138));

        tela2cadastro.setBackground(new java.awt.Color(255, 255, 255));

        usuariocadastro.setBackground(new java.awt.Color(255, 255, 255));
        usuariocadastro.setForeground(new java.awt.Color(0, 0, 0));
        usuariocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariocadastroActionPerformed(evt);
            }
        });

        senhaCadastro.setBackground(new java.awt.Color(0, 0, 0));
        senhaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        senhaCadastro.setForeground(new java.awt.Color(0, 0, 0));
        senhaCadastro.setText("Senha:");

        senhaCasatro1.setBackground(new java.awt.Color(255, 255, 255));
        senhaCasatro1.setForeground(new java.awt.Color(0, 0, 0));
        senhaCasatro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCasatro1ActionPerformed(evt);
            }
        });

        butaoCadastrar.setBackground(new java.awt.Color(0, 51, 153));
        butaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        butaoCadastrar.setText("Cadastar");
        butaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCadastrarActionPerformed(evt);
            }
        });

        usuarioCadastro.setBackground(new java.awt.Color(0, 0, 0));
        usuarioCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarioCadastro.setForeground(new java.awt.Color(0, 0, 0));
        usuarioCadastro.setText("Nome:");

        usuarioCPF.setBackground(new java.awt.Color(0, 0, 0));
        usuarioCPF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarioCPF.setForeground(new java.awt.Color(0, 0, 0));
        usuarioCPF.setText("CPF:");

        usuarioCPFDdigitado.setBackground(new java.awt.Color(255, 255, 255));
        usuarioCPFDdigitado.setForeground(new java.awt.Color(0, 0, 0));
        try {
            usuarioCPFDdigitado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout tela2cadastroLayout = new javax.swing.GroupLayout(tela2cadastro);
        tela2cadastro.setLayout(tela2cadastroLayout);
        tela2cadastroLayout.setHorizontalGroup(
            tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela2cadastroLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela2cadastroLayout.createSequentialGroup()
                        .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaCasatro1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioCadastro)
                            .addComponent(usuariocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioCPF)
                            .addComponent(usuarioCPFDdigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela2cadastroLayout.createSequentialGroup()
                        .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))))
        );
        tela2cadastroLayout.setVerticalGroup(
            tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela2cadastroLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(usuarioCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuariocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioCPFDdigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaCasatro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout tela1CadastroLayout = new javax.swing.GroupLayout(tela1Cadastro);
        tela1Cadastro.setLayout(tela1CadastroLayout);
        tela1CadastroLayout.setHorizontalGroup(
            tela1CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela1CadastroLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(tela2cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        tela1CadastroLayout.setVerticalGroup(
            tela1CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tela1CadastroLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(tela2cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariocadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariocadastroActionPerformed

    private void butaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCadastrarActionPerformed
        // TODO add your handling code here:
        
        //criar um objeto da classe
        
        UsuarioModel usuario = new UsuarioModel();
        //cadastrar os dados dentro da classe FuncionariosModel
        usuario.setNome(usuariocadastro.getText());
        //capturar dados do campo Password Fild
        usuario.setSenha( new String(senhaCasatro1.getPassword()));
        
        
    }//GEN-LAST:event_butaoCadastrarActionPerformed

    private void senhaCasatro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCasatro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCasatro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoCadastrar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel senhaCadastro;
    private javax.swing.JPasswordField senhaCasatro1;
    private javax.swing.JPanel tela1Cadastro;
    private javax.swing.JPanel tela2cadastro;
    private javax.swing.JLabel usuarioCPF;
    private javax.swing.JFormattedTextField usuarioCPFDdigitado;
    private javax.swing.JLabel usuarioCadastro;
    private javax.swing.JTextField usuariocadastro;
    // End of variables declaration//GEN-END:variables
}
