/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaRegistrosImprestimos extends javax.swing.JFrame {

    /**
     * Creates new form RegistrosImprestimos
     */
    public TelaRegistrosImprestimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        textoDataDevolucao = new javax.swing.JPanel();
        paineliconeSyncriaRegistros = new javax.swing.JPanel();
        tituloBibliotecaSyncria = new javax.swing.JLabel();
        iconeBilblioteca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selecionarTurnoRE = new javax.swing.JComboBox<>();
        tituloTurnosRE = new javax.swing.JLabel();
        tituloCodigoDeTurmaRE = new javax.swing.JLabel();
        selecionarTurmaRE = new javax.swing.JComboBox<>();
        tituloAlunoRE = new javax.swing.JLabel();
        tituloDoLivroRE = new javax.swing.JLabel();
        selecionarTituloLivro = new javax.swing.JComboBox<>();
        textoDataRetiradaRE = new javax.swing.JTextField();
        tituloBimestreRE = new javax.swing.JLabel();
        tituloRegistrosRE = new javax.swing.JLabel();
        textoRegistrosRE = new javax.swing.JTextField();
        butaoDataRetiradaRE = new javax.swing.JButton();
        tituloDataDevolucaoRE = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloRegistrosEmprestimos = new javax.swing.JLabel();
        iconeRE = new javax.swing.JLabel();
        textoDataDevolucaoRE = new javax.swing.JTextField();
        selecionarBimestroRE = new javax.swing.JComboBox<>();
        tituloTabelaSituacaoLivrosEmprestadosRE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSituacaoTítuloRE = new javax.swing.JTable();
        tituloTabelaSituacaoDoTitulo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaLocalizacaoLivroBibliotecaRE = new javax.swing.JTable();
        tituloDataRetiradaRE1 = new javax.swing.JLabel();
        selecionarAlunoRE1 = new javax.swing.JComboBox<>();
        tituloTabelaSituacaoAlunoRE = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaSituacaoAlunoRE = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaSituacaoLivrosEmprestadosRE = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaDataTrocaRE = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelaLivrosAlugadosRE = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelaSituacaoRE = new javax.swing.JTable();
        botaoGravar = new javax.swing.JButton();
        botaoRenovar = new javax.swing.JButton();
        botaoDevolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        guiaEmprestimos = new javax.swing.JMenu();
        guiaLivros = new javax.swing.JMenu();
        guiaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBDT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoDataDevolucao.setBackground(new java.awt.Color(204, 204, 204));

        paineliconeSyncriaRegistros.setBackground(new java.awt.Color(208, 224, 235));

        tituloBibliotecaSyncria.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tituloBibliotecaSyncria.setForeground(new java.awt.Color(0, 0, 0));
        tituloBibliotecaSyncria.setText("Biblioteca Syncria");

        iconeBilblioteca.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro_(1)_(2).png")); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\logout_(1).png")); // NOI18N
        jLabel1.setText("Sair");

        javax.swing.GroupLayout paineliconeSyncriaRegistrosLayout = new javax.swing.GroupLayout(paineliconeSyncriaRegistros);
        paineliconeSyncriaRegistros.setLayout(paineliconeSyncriaRegistrosLayout);
        paineliconeSyncriaRegistrosLayout.setHorizontalGroup(
            paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineliconeSyncriaRegistrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconeBilblioteca)
                .addGap(18, 18, 18)
                .addComponent(tituloBibliotecaSyncria, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
        paineliconeSyncriaRegistrosLayout.setVerticalGroup(
            paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineliconeSyncriaRegistrosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeBilblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloBibliotecaSyncria))
                .addGap(12, 12, 12))
            .addGroup(paineliconeSyncriaRegistrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selecionarTurnoRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarTurnoRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarTurnoRE.setForeground(new java.awt.Color(0, 0, 0));
        selecionarTurnoRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATUTINO", "VESPERTINO", "NOTURNO" }));

        tituloTurnosRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloTurnosRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloTurnosRE.setText("Turnos:");

        tituloCodigoDeTurmaRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloCodigoDeTurmaRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloCodigoDeTurmaRE.setText("Codigo da turma:");

        selecionarTurmaRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarTurmaRE.setEditable(true);
        selecionarTurmaRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarTurmaRE.setForeground(new java.awt.Color(0, 0, 0));
        selecionarTurmaRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        selecionarTurmaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarTurmaREActionPerformed(evt);
            }
        });

        tituloAlunoRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloAlunoRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloAlunoRE.setText("Aluno(a):");
        tituloAlunoRE.setToolTipText("");

        tituloDoLivroRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDoLivroRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloDoLivroRE.setText("Título do Livro:");

        selecionarTituloLivro.setBackground(new java.awt.Color(255, 255, 255));
        selecionarTituloLivro.setEditable(true);
        selecionarTituloLivro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarTituloLivro.setForeground(new java.awt.Color(0, 0, 0));

        textoDataRetiradaRE.setBackground(new java.awt.Color(255, 255, 255));
        textoDataRetiradaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataRetiradaREActionPerformed(evt);
            }
        });

        tituloBimestreRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloBimestreRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloBimestreRE.setText("Bimestre:");

        tituloRegistrosRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloRegistrosRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloRegistrosRE.setText("Registro:");

        textoRegistrosRE.setBackground(new java.awt.Color(255, 255, 255));
        textoRegistrosRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRegistrosREActionPerformed(evt);
            }
        });

        butaoDataRetiradaRE.setBackground(new java.awt.Color(255, 255, 255));
        butaoDataRetiradaRE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butaoDataRetiradaRE.setForeground(new java.awt.Color(0, 0, 0));
        butaoDataRetiradaRE.setText("Hoje");

        tituloDataDevolucaoRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDataDevolucaoRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloDataDevolucaoRE.setText("Data de Devolução:");

        jPanel1.setBackground(new java.awt.Color(73, 112, 138));

        tituloRegistrosEmprestimos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloRegistrosEmprestimos.setForeground(new java.awt.Color(0, 0, 0));
        tituloRegistrosEmprestimos.setText("Registros de Empréstimos");

        iconeRE.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\registro_(1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(iconeRE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloRegistrosEmprestimos)
                .addContainerGap(1497, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeRE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tituloRegistrosEmprestimos)
                        .addGap(8, 8, 8)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        textoDataDevolucaoRE.setBackground(new java.awt.Color(255, 255, 255));
        textoDataDevolucaoRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataDevolucaoREActionPerformed(evt);
            }
        });

        selecionarBimestroRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarBimestroRE.setEditable(true);
        selecionarBimestroRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarBimestroRE.setForeground(new java.awt.Color(0, 0, 0));
        selecionarBimestroRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Bimestre", "2º Bimestre", "3º Bimestre", "4º Bimestre", " " }));
        selecionarBimestroRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarBimestroREActionPerformed(evt);
            }
        });

        tituloTabelaSituacaoLivrosEmprestadosRE.setBackground(new java.awt.Color(255, 255, 51));
        tituloTabelaSituacaoLivrosEmprestadosRE.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tituloTabelaSituacaoLivrosEmprestadosRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloTabelaSituacaoLivrosEmprestadosRE.setText("Situação dos Livros Emprestados");
        tituloTabelaSituacaoLivrosEmprestadosRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTabelaSituacaoLivrosEmprestadosREActionPerformed(evt);
            }
        });

        tabelaSituacaoTítuloRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaSituacaoTítuloRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Emprestados", "No Acervo"
            }
        ));
        tabelaSituacaoTítuloRE.setToolTipText("\n");
        jScrollPane1.setViewportView(tabelaSituacaoTítuloRE);

        tituloTabelaSituacaoDoTitulo.setBackground(new java.awt.Color(102, 204, 255));
        tituloTabelaSituacaoDoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloTabelaSituacaoDoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        tituloTabelaSituacaoDoTitulo.setText("Situação do Título");
        tituloTabelaSituacaoDoTitulo.setToolTipText("");
        tituloTabelaSituacaoDoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTabelaSituacaoDoTituloActionPerformed(evt);
            }
        });

        tabelaLocalizacaoLivroBibliotecaRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaLocalizacaoLivroBibliotecaRE.setForeground(new java.awt.Color(0, 0, 0));
        tabelaLocalizacaoLivroBibliotecaRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Localização do LIvro na biblioteca"
            }
        ));
        jScrollPane2.setViewportView(tabelaLocalizacaoLivroBibliotecaRE);

        tituloDataRetiradaRE1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDataRetiradaRE1.setForeground(new java.awt.Color(0, 0, 0));
        tituloDataRetiradaRE1.setText("Data da Retirada:");

        selecionarAlunoRE1.setBackground(new java.awt.Color(255, 255, 255));
        selecionarAlunoRE1.setEditable(true);
        selecionarAlunoRE1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarAlunoRE1.setForeground(new java.awt.Color(0, 0, 0));

        tituloTabelaSituacaoAlunoRE.setBackground(new java.awt.Color(255, 255, 51));
        tituloTabelaSituacaoAlunoRE.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tituloTabelaSituacaoAlunoRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloTabelaSituacaoAlunoRE.setText("Situação do Aluno(a)");
        tituloTabelaSituacaoAlunoRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTabelaSituacaoAlunoREActionPerformed(evt);
            }
        });

        tabelaSituacaoAlunoRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaSituacaoAlunoRE.setForeground(new java.awt.Color(255, 255, 255));
        tabelaSituacaoAlunoRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Emprestados", "Devolvidos", "Devolvendo"
            }
        ));
        jScrollPane4.setViewportView(tabelaSituacaoAlunoRE);

        tabelaSituacaoLivrosEmprestadosRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaSituacaoLivrosEmprestadosRE.setForeground(new java.awt.Color(0, 0, 0));
        tabelaSituacaoLivrosEmprestadosRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null}
            },
            new String [] {
                "Emprestados", "Devolvidos", "Saldo", "Total"
            }
        ));
        tabelaSituacaoLivrosEmprestadosRE.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jScrollPane6.setViewportView(tabelaSituacaoLivrosEmprestadosRE);

        tabelaDataTrocaRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaDataTrocaRE.setForeground(new java.awt.Color(0, 0, 0));
        tabelaDataTrocaRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {null},
                {null}
            },
            new String [] {
                "Troca Data"
            }
        ));
        tabelaDataTrocaRE.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jScrollPane7.setViewportView(tabelaDataTrocaRE);

        tabelaLivrosAlugadosRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaLivrosAlugadosRE.setForeground(new java.awt.Color(0, 0, 0));
        tabelaLivrosAlugadosRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {null},
                {null}
            },
            new String [] {
                "LIVROS ALUGADOS PELO ALUNO(A)"
            }
        ));
        tabelaLivrosAlugadosRE.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jScrollPane8.setViewportView(tabelaLivrosAlugadosRE);

        tabelaSituacaoRE.setBackground(new java.awt.Color(255, 255, 255));
        tabelaSituacaoRE.setForeground(new java.awt.Color(0, 0, 0));
        tabelaSituacaoRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {""},
                {null},
                {null}
            },
            new String [] {
                "Situação"
            }
        ));
        tabelaSituacaoRE.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jScrollPane9.setViewportView(tabelaSituacaoRE);

        botaoGravar.setBackground(new java.awt.Color(255, 204, 0));
        botaoGravar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoGravar.setForeground(new java.awt.Color(0, 0, 0));
        botaoGravar.setText("GRAVAR");

        botaoRenovar.setBackground(new java.awt.Color(51, 153, 255));
        botaoRenovar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoRenovar.setForeground(new java.awt.Color(0, 0, 0));
        botaoRenovar.setText("Renovar");
        botaoRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRenovarActionPerformed(evt);
            }
        });

        botaoDevolver.setBackground(new java.awt.Color(102, 255, 102));
        botaoDevolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoDevolver.setForeground(new java.awt.Color(0, 0, 0));
        botaoDevolver.setText("Devolver");
        botaoDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textoDataDevolucaoLayout = new javax.swing.GroupLayout(textoDataDevolucao);
        textoDataDevolucao.setLayout(textoDataDevolucaoLayout);
        textoDataDevolucaoLayout.setHorizontalGroup(
            textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paineliconeSyncriaRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                        .addComponent(textoDataRetiradaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(butaoDataRetiradaRE))
                                    .addComponent(selecionarTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloDoLivroRE)
                                    .addComponent(tituloDataDevolucaoRE)
                                    .addComponent(tituloRegistrosRE)
                                    .addComponent(textoRegistrosRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(222, 222, 222)
                                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloTabelaSituacaoAlunoRE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(selecionarBimestroRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloBimestreRE)
                            .addComponent(textoDataDevolucaoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(botaoDevolver)
                                .addGap(18, 18, 18)
                                .addComponent(botaoRenovar)
                                .addGap(202, 202, 202))))
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloTurnosRE)
                            .addComponent(tituloDataRetiradaRE1)
                            .addComponent(tituloAlunoRE)
                            .addComponent(selecionarTurmaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloCodigoDeTurmaRE)
                            .addComponent(selecionarAlunoRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(selecionarTurnoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(botaoGravar)))
                        .addGap(125, 125, 125)
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(tituloTabelaSituacaoDoTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(357, 357, 357))
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tituloTabelaSituacaoLivrosEmprestadosRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        textoDataDevolucaoLayout.setVerticalGroup(
            textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                .addComponent(paineliconeSyncriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addComponent(tituloTurnosRE)
                        .addGap(18, 18, 18)
                        .addComponent(selecionarTurnoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(tituloCodigoDeTurmaRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarTurmaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloTabelaSituacaoLivrosEmprestadosRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoGravar))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tituloAlunoRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarAlunoRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloDataRetiradaRE1))
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(tituloTabelaSituacaoDoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDataRetiradaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butaoDataRetiradaRE)
                    .addComponent(botaoDevolver)
                    .addComponent(botaoRenovar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloDoLivroRE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloTabelaSituacaoAlunoRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(textoDataDevolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addComponent(selecionarTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tituloRegistrosRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoRegistrosRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(tituloDataDevolucaoRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoDataDevolucaoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloBimestreRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecionarBimestroRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(textoDataDevolucaoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        guiaEmprestimos.setText("| Registros Emprestimos |");
        guiaEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaEmprestimosMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaEmprestimos);

        guiaLivros.setText("Listas de Livros Emprestados |");
        guiaLivros.setToolTipText("");
        guiaLivros.setActionCommand("Listas de livros Empréstados  |");
        guiaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaLivrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaLivros);

        guiaLivrosAcervo.setText(" Listas de livros Acervos |");
        guiaLivrosAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaLivrosAcervoMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaLivrosAcervo);

        guiaRankingLeitores.setText("Ranking dos Leitores  |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaRankingLeitores);

        guiaBDT.setText("Banco de dados Turma |");
        guiaBDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBDTMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaBDT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoDataDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaLivrosMouseClicked
        // TODO add your handling code here:
        // criando um objeto da tela1 par tela2
        ListaDeLivrosEmprestados tela1ParaTela2 = new ListaDeLivrosEmprestados ();

// abrindo a tela
      tela1ParaTela2.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaLivrosMouseClicked

    private void guiaLivrosAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaLivrosAcervoMouseClicked
        // TODO add your handling code here:
        ListaDeLivrosNoAcervo tela1ParaTela3 = new ListaDeLivrosNoAcervo ();

// abrindo a tela
      tela1ParaTela3.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaLivrosAcervoMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    private void guiaBDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBDTMouseClicked
        // TODO add your handling code here:
        BancoDeDadosDasTurmas tela1ParaTela5 = new BancoDeDadosDasTurmas  ();

// abrindo a tela
   tela1ParaTela5.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaBDTMouseClicked

    private void guiaEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaEmprestimosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaEmprestimosMouseClicked

    private void textoRegistrosREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRegistrosREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRegistrosREActionPerformed

    private void textoDataRetiradaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataRetiradaREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataRetiradaREActionPerformed

    private void selecionarTurmaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarTurmaREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarTurmaREActionPerformed

    private void textoDataDevolucaoREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataDevolucaoREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataDevolucaoREActionPerformed

    private void selecionarBimestroREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarBimestroREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarBimestroREActionPerformed

    private void tituloTabelaSituacaoLivrosEmprestadosREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTabelaSituacaoLivrosEmprestadosREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTabelaSituacaoLivrosEmprestadosREActionPerformed

    private void tituloTabelaSituacaoDoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTabelaSituacaoDoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTabelaSituacaoDoTituloActionPerformed

    private void tituloTabelaSituacaoAlunoREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTabelaSituacaoAlunoREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTabelaSituacaoAlunoREActionPerformed

    private void botaoRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRenovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRenovarActionPerformed

    private void botaoDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrosImprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDevolver;
    private javax.swing.JButton botaoGravar;
    private javax.swing.JButton botaoRenovar;
    private javax.swing.JButton butaoDataRetiradaRE;
    private javax.swing.JMenu guiaBDT;
    private javax.swing.JMenu guiaEmprestimos;
    private javax.swing.JMenu guiaLivros;
    private javax.swing.JMenu guiaLivrosAcervo;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JLabel iconeBilblioteca;
    private javax.swing.JLabel iconeRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel paineliconeSyncriaRegistros;
    private javax.swing.JComboBox<String> selecionarAlunoRE1;
    private javax.swing.JComboBox<String> selecionarBimestroRE;
    private javax.swing.JComboBox<String> selecionarTituloLivro;
    private javax.swing.JComboBox<String> selecionarTurmaRE;
    private javax.swing.JComboBox<String> selecionarTurnoRE;
    private javax.swing.JTable tabelaDataTrocaRE;
    private javax.swing.JTable tabelaLivrosAlugadosRE;
    private javax.swing.JTable tabelaLocalizacaoLivroBibliotecaRE;
    private javax.swing.JTable tabelaSituacaoAlunoRE;
    private javax.swing.JTable tabelaSituacaoLivrosEmprestadosRE;
    private javax.swing.JTable tabelaSituacaoRE;
    private javax.swing.JTable tabelaSituacaoTítuloRE;
    private javax.swing.JPanel textoDataDevolucao;
    private javax.swing.JTextField textoDataDevolucaoRE;
    private javax.swing.JTextField textoDataRetiradaRE;
    private javax.swing.JTextField textoRegistrosRE;
    private javax.swing.JLabel tituloAlunoRE;
    private javax.swing.JLabel tituloBibliotecaSyncria;
    private javax.swing.JLabel tituloBimestreRE;
    private javax.swing.JLabel tituloCodigoDeTurmaRE;
    private javax.swing.JLabel tituloDataDevolucaoRE;
    private javax.swing.JLabel tituloDataRetiradaRE1;
    private javax.swing.JLabel tituloDoLivroRE;
    private javax.swing.JLabel tituloRegistrosEmprestimos;
    private javax.swing.JLabel tituloRegistrosRE;
    private javax.swing.JTextField tituloTabelaSituacaoAlunoRE;
    private javax.swing.JTextField tituloTabelaSituacaoDoTitulo;
    private javax.swing.JTextField tituloTabelaSituacaoLivrosEmprestadosRE;
    private javax.swing.JLabel tituloTurnosRE;
    // End of variables declaration//GEN-END:variables
}
