/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaRegistrosImprestimos extends javax.swing.JFrame {

    /**
     * Creates new form RegistrosImprestimos
     */
    public TelaRegistrosImprestimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelRegistrosImprestimos = new javax.swing.JPanel();
        paineliconeSyncriaRegistros = new javax.swing.JPanel();
        tituloBibliotecaSyncria = new javax.swing.JLabel();
        iconeBilblioteca = new javax.swing.JLabel();
        tituloRegistrosImprestimos = new javax.swing.JLabel();
        selecionarTurnoRE = new javax.swing.JComboBox<>();
        tituloTurnosRE = new javax.swing.JLabel();
        tituloCodigoDeTurmaRE = new javax.swing.JLabel();
        selecionarTurmaRE = new javax.swing.JComboBox<>();
        tituloAlunoRE = new javax.swing.JLabel();
        tituloDataRetiradaRE = new javax.swing.JLabel();
        selecionarAlunoRE = new javax.swing.JComboBox<>();
        iconeRE = new javax.swing.JLabel();
        textoDataRetiradaRE = new javax.swing.JTextField();
        tituloDataDevolucaoRE = new javax.swing.JLabel();
        textoDataDevolucaoRE = new javax.swing.JTextField();
        tituloRegistrosRE = new javax.swing.JLabel();
        textoRegistrosRE = new javax.swing.JTextField();
        butaoDataRetiradaRE = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        guiaEmprestimos = new javax.swing.JMenu();
        guiaLivros = new javax.swing.JMenu();
        guiaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBDT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelRegistrosImprestimos.setBackground(new java.awt.Color(73, 112, 138));

        paineliconeSyncriaRegistros.setBackground(new java.awt.Color(208, 224, 235));

        tituloBibliotecaSyncria.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tituloBibliotecaSyncria.setForeground(new java.awt.Color(0, 0, 0));
        tituloBibliotecaSyncria.setText("Biblioteca Syncria");

        iconeBilblioteca.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro_(1)_(2).png")); // NOI18N

        javax.swing.GroupLayout paineliconeSyncriaRegistrosLayout = new javax.swing.GroupLayout(paineliconeSyncriaRegistros);
        paineliconeSyncriaRegistros.setLayout(paineliconeSyncriaRegistrosLayout);
        paineliconeSyncriaRegistrosLayout.setHorizontalGroup(
            paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineliconeSyncriaRegistrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconeBilblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloBibliotecaSyncria, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paineliconeSyncriaRegistrosLayout.setVerticalGroup(
            paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paineliconeSyncriaRegistrosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paineliconeSyncriaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconeBilblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloBibliotecaSyncria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        tituloRegistrosImprestimos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloRegistrosImprestimos.setForeground(new java.awt.Color(0, 0, 0));
        tituloRegistrosImprestimos.setText("Registros de Imprestimos");

        selecionarTurnoRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarTurnoRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarTurnoRE.setForeground(new java.awt.Color(0, 0, 0));
        selecionarTurnoRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATUTINO", "VESPERTINO", "NOTURNO" }));

        tituloTurnosRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloTurnosRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloTurnosRE.setText("Turnos:");

        tituloCodigoDeTurmaRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloCodigoDeTurmaRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloCodigoDeTurmaRE.setText("Codigo da turma:");

        selecionarTurmaRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarTurmaRE.setEditable(true);
        selecionarTurmaRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarTurmaRE.setForeground(new java.awt.Color(0, 0, 0));
        selecionarTurmaRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        selecionarTurmaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarTurmaREActionPerformed(evt);
            }
        });

        tituloAlunoRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloAlunoRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloAlunoRE.setText("Aluno(a):");
        tituloAlunoRE.setToolTipText("");

        tituloDataRetiradaRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDataRetiradaRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloDataRetiradaRE.setText("Data da Retirada:");

        selecionarAlunoRE.setBackground(new java.awt.Color(255, 255, 255));
        selecionarAlunoRE.setEditable(true);
        selecionarAlunoRE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selecionarAlunoRE.setForeground(new java.awt.Color(0, 0, 0));

        iconeRE.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\registrado (1) (1).png")); // NOI18N

        textoDataRetiradaRE.setBackground(new java.awt.Color(255, 255, 255));
        textoDataRetiradaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataRetiradaREActionPerformed(evt);
            }
        });

        tituloDataDevolucaoRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloDataDevolucaoRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloDataDevolucaoRE.setText("Data de Devolução:");

        textoDataDevolucaoRE.setBackground(new java.awt.Color(255, 255, 255));
        textoDataDevolucaoRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDataDevolucaoREActionPerformed(evt);
            }
        });

        tituloRegistrosRE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloRegistrosRE.setForeground(new java.awt.Color(0, 0, 0));
        tituloRegistrosRE.setText("Registro:");

        textoRegistrosRE.setBackground(new java.awt.Color(255, 255, 255));
        textoRegistrosRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoRegistrosREActionPerformed(evt);
            }
        });

        butaoDataRetiradaRE.setBackground(new java.awt.Color(255, 255, 255));
        butaoDataRetiradaRE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butaoDataRetiradaRE.setForeground(new java.awt.Color(0, 0, 0));
        butaoDataRetiradaRE.setText("Hoje");

        javax.swing.GroupLayout painelRegistrosImprestimosLayout = new javax.swing.GroupLayout(painelRegistrosImprestimos);
        painelRegistrosImprestimos.setLayout(painelRegistrosImprestimosLayout);
        painelRegistrosImprestimosLayout.setHorizontalGroup(
            painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paineliconeSyncriaRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloDataDevolucaoRE)
                        .addGap(18, 18, 18)
                        .addComponent(textoDataDevolucaoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(iconeRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tituloRegistrosImprestimos))
                    .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloDataRetiradaRE)
                            .addComponent(tituloRegistrosRE)
                            .addComponent(tituloAlunoRE)
                            .addComponent(tituloCodigoDeTurmaRE)
                            .addComponent(tituloTurnosRE))
                        .addGap(18, 18, 18)
                        .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionarTurmaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecionarTurnoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecionarAlunoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                                .addComponent(textoDataRetiradaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(butaoDataRetiradaRE))
                            .addComponent(textoRegistrosRE, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        painelRegistrosImprestimosLayout.setVerticalGroup(
            painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRegistrosImprestimosLayout.createSequentialGroup()
                .addComponent(paineliconeSyncriaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconeRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloRegistrosImprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionarTurnoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTurnosRE))
                .addGap(34, 34, 34)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCodigoDeTurmaRE)
                    .addComponent(selecionarTurmaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selecionarAlunoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlunoRE))
                .addGap(32, 32, 32)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloDataRetiradaRE)
                    .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoDataRetiradaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butaoDataRetiradaRE)))
                .addGap(33, 33, 33)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoRegistrosRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloRegistrosRE))
                .addGap(33, 33, 33)
                .addGroup(painelRegistrosImprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoDataDevolucaoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloDataDevolucaoRE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        guiaEmprestimos.setText("| Registros Emprestimos |");
        jMenuBar1.add(guiaEmprestimos);

        guiaLivros.setText("Listas de Livros Emprestados |");
        guiaLivros.setToolTipText("");
        guiaLivros.setActionCommand("Listas de livros Empréstados  |");
        guiaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaLivrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaLivros);

        guiaLivrosAcervo.setText(" Listas de livros Acervos |");
        guiaLivrosAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaLivrosAcervoMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaLivrosAcervo);

        guiaRankingLeitores.setText("Ranking dos Leitores |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaRankingLeitores);

        guiaBDT.setText("Banco de dados Turma |");
        guiaBDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBDTMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaBDT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelRegistrosImprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelRegistrosImprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarTurmaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarTurmaREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarTurmaREActionPerformed

    private void textoDataRetiradaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataRetiradaREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataRetiradaREActionPerformed

    private void textoDataDevolucaoREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDataDevolucaoREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDataDevolucaoREActionPerformed

    private void textoRegistrosREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoRegistrosREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoRegistrosREActionPerformed

    private void guiaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaLivrosMouseClicked
        // TODO add your handling code here:
        // criando um objeto da tela1 par tela2
        ListaDeLivrosEmprestados tela1ParaTela2 = new ListaDeLivrosEmprestados ();

// abrindo a tela
      tela1ParaTela2.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaLivrosMouseClicked

    private void guiaLivrosAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaLivrosAcervoMouseClicked
        // TODO add your handling code here:
        ListaDeLivrosNoAcervo tela1ParaTela3 = new ListaDeLivrosNoAcervo ();

// abrindo a tela
      tela1ParaTela3.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaLivrosAcervoMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    private void guiaBDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBDTMouseClicked
        // TODO add your handling code here:
        BancoDeDadosDasTurmas tela1ParaTela5 = new BancoDeDadosDasTurmas  ();

// abrindo a tela
   tela1ParaTela5.setVisible(true);
        
// fechar a tela de atual
         dispose();
    }//GEN-LAST:event_guiaBDTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrosImprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrosImprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoDataRetiradaRE;
    private javax.swing.JMenu guiaBDT;
    private javax.swing.JMenu guiaEmprestimos;
    private javax.swing.JMenu guiaLivros;
    private javax.swing.JMenu guiaLivrosAcervo;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JLabel iconeBilblioteca;
    private javax.swing.JLabel iconeRE;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel painelRegistrosImprestimos;
    private javax.swing.JPanel paineliconeSyncriaRegistros;
    private javax.swing.JComboBox<String> selecionarAlunoRE;
    private javax.swing.JComboBox<String> selecionarTurmaRE;
    private javax.swing.JComboBox<String> selecionarTurnoRE;
    private javax.swing.JTextField textoDataDevolucaoRE;
    private javax.swing.JTextField textoDataRetiradaRE;
    private javax.swing.JTextField textoRegistrosRE;
    private javax.swing.JLabel tituloAlunoRE;
    private javax.swing.JLabel tituloBibliotecaSyncria;
    private javax.swing.JLabel tituloCodigoDeTurmaRE;
    private javax.swing.JLabel tituloDataDevolucaoRE;
    private javax.swing.JLabel tituloDataRetiradaRE;
    private javax.swing.JLabel tituloRegistrosImprestimos;
    private javax.swing.JLabel tituloRegistrosRE;
    private javax.swing.JLabel tituloTurnosRE;
    // End of variables declaration//GEN-END:variables
}
