/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tela1Cadastro = new javax.swing.JPanel();
        tela2cadastro = new javax.swing.JPanel();
        escrevaGmailCastro = new javax.swing.JTextField();
        senhaCadastro = new javax.swing.JLabel();
        senhaCasatro1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        butaoSenha = new javax.swing.JButton();
        senhaCadastro1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tela1Cadastro.setBackground(new java.awt.Color(73, 112, 138));

        tela2cadastro.setBackground(new java.awt.Color(255, 255, 255));

        escrevaGmailCastro.setBackground(new java.awt.Color(255, 255, 255));
        escrevaGmailCastro.setForeground(new java.awt.Color(0, 0, 0));
        escrevaGmailCastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escrevaGmailCastroActionPerformed(evt);
            }
        });

        senhaCadastro.setBackground(new java.awt.Color(0, 0, 0));
        senhaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        senhaCadastro.setForeground(new java.awt.Color(0, 0, 0));
        senhaCadastro.setText("Senha:");

        senhaCasatro1.setBackground(new java.awt.Color(255, 255, 255));
        senhaCasatro1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Syncria_-_Technology (2).png")); // NOI18N

        butaoSenha.setBackground(new java.awt.Color(0, 51, 153));
        butaoSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butaoSenha.setForeground(new java.awt.Color(255, 255, 255));
        butaoSenha.setText("Cadastar");
        butaoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoSenhaActionPerformed(evt);
            }
        });

        senhaCadastro1.setBackground(new java.awt.Color(0, 0, 0));
        senhaCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        senhaCadastro1.setForeground(new java.awt.Color(0, 0, 0));
        senhaCadastro1.setText("E-mail:");

        javax.swing.GroupLayout tela2cadastroLayout = new javax.swing.GroupLayout(tela2cadastro);
        tela2cadastro.setLayout(tela2cadastroLayout);
        tela2cadastroLayout.setHorizontalGroup(
            tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela2cadastroLayout.createSequentialGroup()
                .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela2cadastroLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhaCasatro1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela2cadastroLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(butaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tela2cadastroLayout.createSequentialGroup()
                .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tela2cadastroLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(senhaCadastro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escrevaGmailCastro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tela2cadastroLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        tela2cadastroLayout.setVerticalGroup(
            tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela2cadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaCadastro1)
                    .addComponent(escrevaGmailCastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(tela2cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaCasatro1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout tela1CadastroLayout = new javax.swing.GroupLayout(tela1Cadastro);
        tela1Cadastro.setLayout(tela1CadastroLayout);
        tela1CadastroLayout.setHorizontalGroup(
            tela1CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela1CadastroLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(tela2cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tela1CadastroLayout.setVerticalGroup(
            tela1CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tela1CadastroLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(tela2cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1Cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela1Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escrevaGmailCastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escrevaGmailCastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escrevaGmailCastroActionPerformed

    private void butaoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoSenha;
    private javax.swing.JTextField escrevaGmailCastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel senhaCadastro;
    private javax.swing.JLabel senhaCadastro1;
    private javax.swing.JPasswordField senhaCasatro1;
    private javax.swing.JPanel tela1Cadastro;
    private javax.swing.JPanel tela2cadastro;
    // End of variables declaration//GEN-END:variables
}
